<a href="https://colab.research.google.com/github/vanshika14168/Machine_Learning/blob/main/houseprice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [44]:
from google.colab import files
uploaded=files.upload()
filename=list(uploaded.keys())[0]
df=pd.read_csv(filename)

Saving houseprice.csv to houseprice.csv

In [45]:
df.head()

   area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         5   18  610000
3  3600         3   30  595000
4  4000         5    8  760000

In [47]:
df.tail()

   area  bedrooms  age   price
1  3000         4   15  565000
2  3200         5   18  610000
3  3600         3   30  595000
4  4000         5    8  760000
5  4100         6    8  810000

In [48]:
df.sample()

   area  bedrooms  age   price
1  3000         4   15  565000

In [49]:
df.sample(4)

   area  bedrooms  age   price
5  4100         6    8  810000
1  3000         4   15  565000
0  2600         3   20  550000
2  3200         5   18  610000

In [50]:
df.shape

(6, 4)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int64
 1   bedrooms  6 non-null      int64
 2   age       6 non-null      int64
 3   price     6 non-null      int64
dtypes: int64(4)
memory usage: 324.0 bytes

In [52]:
df.describe()

              area  bedrooms        age          price
count     6.000000  6.000000   6.000000       6.000000
mean   3416.666667  4.333333  16.500000  648333.333333
std     587.934237  1.211060   8.288546  109117.673484
min    2600.000000  3.000000   8.000000  550000.000000
25%    3050.000000  3.250000   9.750000  572500.000000
50%    3400.000000  4.500000  16.500000  602500.000000
75%    3900.000000  5.000000  19.500000  722500.000000
max    4100.000000  6.000000  30.000000  810000.000000

In [53]:
df.isnull()

    area  bedrooms    age  price
0  False     False  False  False
1  False     False  False  False
2  False     False  False  False
3  False     False  False  False
4  False     False  False  False
5  False     False  False  False

In [54]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df[['area','bedrooms']]

   area  bedrooms
0  2600         3
1  3000         4
2  3200         5
3  3600         3
4  4000         5
5  4100         6

In [57]:
df['area'].value_counts()

area
2600    1
3000    1
3200    1
3600    1
4000    1
4100    1
Name: count, dtype: int64

In [58]:
X=df.drop('price',axis=1)
y=df['price']

In [59]:
type(X)

pandas.core.frame.DataFrame

In [60]:
type(y)

pandas.core.series.Series

In [61]:
X.shape

(6, 3)

In [62]:
y.shape

(6,)

In [102]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [103]:
X_train

   area  bedrooms  age
5  4100         6    8
2  3200         5   18
4  4000         5    8
3  3600         3   30

In [104]:
X_train.shape

(4, 3)

In [92]:
y_train.shape

(5,)

In [105]:
X_test.shape

(2, 3)

In [106]:
y_test.shape

(2,)

In [107]:
model=LinearRegression()

In [108]:
model.fit(X_train,y_train)

LinearRegression()

In [109]:
y_pre=model.predict(X_test)

In [110]:
print(y_pre)

[439230.76923077 547243.58974359]

In [111]:
print(list(y_test),end="")

[550000, 565000]

In [112]:
result=r2_score(y_pre,y_test)

In [113]:
print(result)

-1.1574288758376712