<a href="https://colab.research.google.com/github/vanshika14168/Machine_Learning/blob/main/label_encoading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import files
uploaded=files.upload()
filename=list(uploaded.keys())[0]
df=pd.read_csv(filename)

Saving homeprices_new.csv to homeprices_new.csv

In [2]:
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

In [5]:
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [6]:
df.tail()

            town  area   price
8   west windsor  3600  710000
9    robinsville  2600  575000
10   robinsville  2900  600000
11   robinsville  3100  620000
12   robinsville  3600  695000

In [7]:
df.sample(8)

               town  area   price
7      west windsor  3300  650000
3   monroe township  3600  680000
10      robinsville  2900  600000
1   monroe township  3000  565000
0   monroe township  2600  550000
4   monroe township  4000  725000
11      robinsville  3100  620000
9       robinsville  2600  575000

In [8]:
df.shape

(13, 3)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   town    13 non-null     int64
 1   area    13 non-null     int64
 2   price   13 non-null     int64
dtypes: int64(3)
memory usage: 444.0 bytes

In [11]:
df.describe()

              area          price
count    13.000000      13.000000
mean   3146.153846  629230.769231
std     453.900475   57621.109914
min    2600.000000  550000.000000
25%    2800.000000  585000.000000
50%    3100.000000  615000.000000
75%    3600.000000  680000.000000
max    4000.000000  725000.000000

In [41]:
df.isnull().sum()

town     0
area     0
price    0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [43]:
df['town'].value_counts()

town
0    5
2    4
1    4
Name: count, dtype: int64

In [44]:
model=LinearRegression()

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
le=LabelEncoder()

In [47]:
df['town']=le.fit_transform(df['town'])

In [48]:
df['town']

0     0
1     0
2     0
3     0
4     0
5     2
6     2
7     2
8     2
9     1
10    1
11    1
12    1
Name: town, dtype: int64

In [49]:
df.head()

   town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000
3     0  3600  680000
4     0  4000  725000

In [50]:
X=df.drop('price',axis=1)
y=df['price']

In [51]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [52]:
model=LinearRegression()

In [53]:
model.fit(X_train,y_train)

LinearRegression()

In [54]:
y_pre=model.predict(X_test)

In [56]:
result=r2_score(y_pre,y_test)

In [57]:
print(result)

0.8139744014213203